name: superheroes
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.1
  provider: ^5.0.0
  google_fonts: ^4.0.4
  http: ^0.13.0
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  golden_toolkit: ^0.15.0

flutter:

  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env

